apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {

    dataBinding {
        enabled = true
    }
    packagingOptions {
        jniLibs {
            pickFirsts += ['**/*.so']
        }
    }


    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        compileSdk rootProject.ext.compileSdkVersion

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'consumer-rules.pro'
        multiDexEnabled true
        buildConfigField "String", "PUBLIC_API_KEY", "\"${getPublicApiKey(project)}\""
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            jniDebuggable true
        }
        dev {
            initWith debug
            matchingFallbacks = ['debug']
        }
        noTv {
            initWith release
            matchingFallbacks = ['release']
        }
    }
    namespace 'com.video.offline.videoplayer.donations'
    buildFeatures {
        aidl true
        buildConfig true
    }
}

static def getPublicApiKey(project) {
   return System.getenv('K8S_SECRET_VLC_PLAYSTORE_PUBLIC_API_KEY') ?:  project.properties['vlc_playstore_public_api_key'] ?: ""
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation project(':application:tools')

    implementation "androidx.core:core-ktx:$rootProject.ext.androidxCoreVersion"
    implementation "androidx.appcompat:appcompat:$rootProject.ext.appCompatVersion"
    testImplementation "junit:junit:$rootProject.ext.junitVersion"
    androidTestImplementation "androidx.test.ext:junit:$rootProject.ext.junitExtVersion"
    androidTestImplementation "androidx.test.espresso:espresso-core:$rootProject.ext.espressoVersion"

}